Fixed issues with yarn module and build errors.
Adapted LauncherModel to changes in @lumino/algorithm
by switching to IterableIterator and using iter().
Also, addressed the following build error:
  Property 'id' does not exist on type 'IteratorReturnResult<any>'.

69       if (widget.id === 'jp-MainLogo') {
  Property 'node' does not exist on type 'IteratorReturnResult<any>'.

71           container: widget.node,
  Object literal may only specify known properties, and 'justify' does not exist in type 'IProps'.

72           justify: 'center',